# Generated by Django 2.0.3 on 2018-04-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.IntegerField()),
                ('paths', models.TextField(default='{}')),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
